# port
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:h2:mem:refactorlibrary;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

---

server:
  port: 8090
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost/refactorlibrary"
    username: "root"
    password: "4788"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# view location
view:
  spring:
    thymeleaf:
      suffix: .html

# encoding korean
encoding:
  spring:
    http:
      encoding:
        charset: UTF-8
    servlet:
      filter:
        character:
          encoding:
            enabled: true
            force-request: true
            force-response: true
            encoding: UTF-8
            force: true

# "localhost:port" + "/" <-
url:
  server:
    servlet:
      context-path: /
